### ISSUE TITLE
Idea: `pkg-pr-new update` for library users

### ISSUE THREAD

**Issue by sevenc-nanashi** [stackblitz-labs/pkg.pr.new#155]
It would be great if there is `pkg-pr-new update` command, which does:
- Detect branch or pr number from `package.json` (Adding some parameters?: `https://pkg.pr.new/sevenc-nanashi/vite-plugin-hmrify@114bbfe?branch=main`)
- Get the latest commit sha of specified branch or pr, and replace the URL in `package.json`: `https://pkg.pr.new/sevenc-nanashi/vite-plugin-hmrify@1234578?branch=main`

(Thank you for great service, I use this for development release)

**Comment by Aslemammad** [comment]
That's really interesting! Maybe at some point we can have this! 

The reason I think this is not high priority, is that pkg-pr-new is not a package manager, and it is expected from users to check the PRs they are receiving releases from regularly to see if any progress has been made in the PR itself. And then when merged, they remove the continuous release they have been using. 

So pkg-pr-new usage should be temporary and not permanently like the way we use npm/yarn/pnpm. Since pkg.pr.new also removes packages after 6 months at most.

**Comment by theoephraim** [comment]
maybe not _update_ but some additional tooling to help flip dependencies back and forth between published `pkg.pr.new` and local `link:` style paths (for pnpm at least) could be helpful. When building tools that interact with deployment platforms like vercel/netlify, I'm often having to flip back and forth to verify my local fixes are working on the actual platform.

I'll definitely be building these scripts for myself, so I'll try to determine if there's any nice way to generalize it.

**Comment by Aslemammad** [comment]
@theoephraim could you give more context on your usecase?

**Comment by theoephraim** [comment]
Sure! The [tool I'm working on](https://dmno.dev) has some plugins that interact a lot with the external build and runtimes of platforms like Vercel and Netlify, some features of which are not possible to fully replicate locally. So my workflow when testing certain features involves doing development locally, and then eventually pushing a commit to the remote platforms (or to github) to trigger a remote build in order to verify it works there.

So imagine 2 repos:
- `dmno-monorepo` - monorepo with various packages, like `dmno-core`, `dmno-foo-integration`, etc
- `dmno-test-repo` - example repo that relies on packages published from `dmno-monorepo`

On my local filesystem, these folders are sitting next to each other, so (using pnpm) I have package.json dependencies in `dmno-test-repo` using the `link:` protocol, for example:
```
  "dmno-core": "link:../dmno-monorepo/packages/core",
  "dmno-foo-integration": "link:../dmno-monorepo/packages/integrations/foo",
```

To test these packages on the remote platforms without publishing to npm, I can change these deps to install from a tarball. Previously I've been running some local scripts that build the packages in `dmno-monorepo` and push tarballs somewhere, and then swap the dependencies to those URLs. It's fine, but all very tedious. Especially because my test repo is actually a monorepo with many child repos testing various cases.

I can imagine some tooling which would help swap these dependencies in my package.json file(s) back and forth between `pkg.pr.new` URLs and my local links (or back to normal npm deps). I haven't thought it through fully yet, but I could imagine setting the `pkg.pr.new` ref to use based on the current checked out branch of the local copy of the repo, passed in flags/args, or even showing an interactive CLI menu that lets you select from a list of the available options.

This might end up making more sense as an additional library rather than in the pkg-pr-new core, especially since this module is intended to be run via `npx` rather than installed as a local dev dependency, but worth discussing here regardless :)

Regarding the intial suggestion above - I could also imagine rolling into this tool the ability to check if the branch or PR being referenced in the pkg.pr.new url and if so, updating the dependency back to the latest npm release.

**Comment by Aslemammad** [comment]
I love how it supports a broader workflow for developers and handle many things in a handy way, but I see so many complexities being grown out of this when brought in pkg.pr.new which makes it out of scope.

I'm really excited to see what you come up with as a cli tool.

**Comment by Aslemammad** [comment]
I'll close this issue, feel free to open it later when there are updates on this! Thank you so much ❤️
