### ISSUE TITLE
Proper yarn support

### ISSUE THREAD

**Issue by Aslemammad** [stackblitz-labs/pkg.pr.new#168]
yarn needs .tgz at the end of urls. 

It was supported before, but now apparently it does not work in pkg.pr.new! 

I guess this is completely wrong:

```ts
const packageKey = `${params.owner}:${params.repo}:${refOrSha}:${packageName.split(".tgz")[0]}`;

```

**Comment by theoephraim** [comment]
Trying to use a preview release via yarn and it was not working. Found this and adding `.tgz` to the url does work - although this should be mentioned somewhere in the docs. However we have another problem, which is that if you are releasing a set of packages from a monorepo, the additional package dependencies pulled in by the main package do not have ".tgz" in their urls, so that breaks.
